=== HetBenkt/appworks-customizations/ToolExportImport/docs/mapping.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mapping">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="entity">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string" />
              <xs:element name="can_have_content" type="xs:boolean" />
              <xs:element name="properties">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="property">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="from" type="xs:string" />
                          <xs:element name="to" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== HetBenkt/appworks-customizations/ToolExportImport/docs/mapping.xml
<?xml version="1.0" encoding="UTF-8" ?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="mapping.xsd">
	<entity>
		<name>category</name>
		<can_have_content>true</can_have_content>
		<properties>
			<property>
				<from>cat_name</from>
				<to>cat_name</to>
			</property>
			<property>
				<from>cat_description</from>
				<to>cat_description</to>
			</property>
		</properties>
	</entity>
	<entity>
		<name>order</name>
		<can_have_content>false</can_have_content>
		<properties>
			<property>
				<from>order_name</from>
				<to>order_name</to>
			</property>
			<property>
				<from>order_quantity</from>
				<to>order_quantity</to>
			</property>
		</properties>
	</entity>
</mapping>
